# This workflow will build a .NET project, create artifacts, and publish DLLs to a release

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Capture output path (optional, adjust based on your needs)
        uses: actions/runner-os@v3
        with:
          secrets: ${{ secrets.<YOUR_SECRET_NAME> }}
      - name: Upload built DLLs
        uses: actions/upload-artifact@v3
        with:
          name: built-dlls
          path: ${{ env.output_path }}/*.dll 

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: built-dlls
      - name: Create release (only on push to master)
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }} - Built DLLs
          body: ${{ steps.build.outputs.build-output }}
          draft: false
          prerelease: true
          file_glob: '**/*.dll'
