name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Upload built DLLs
        uses: actions/upload-artifact@v2
        with:
          name: built-dlls
          path: "**/bin/Release/**/*.dll"

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download built DLLs
        uses: actions/download-artifact@v2
        with:
          name: built-dlls

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.release }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }} - Built DLLs
          body: |
            Release with built DLLs
          draft: false
          prerelease: true
